server:
  port: 3344
spring:
  application:
    name: microservicecloud-zuul-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:HDL194067908/mircoservicecloud-config.git

