server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
zuul:
  routes:
    dept: 
      service-id: microservicecloud-dept
      path: /mydept/** 
  ignored-services: microservicecloud-dept
  prefix: /hdl
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true #访问路径可以显示


info:
  app.name: hdl-microcoud
  company.name: www.hdl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$